import { readFileSync, existsSync, statSync } from 'fs';
import { join } from 'path';
import { parseFrontmatter } from '../vault/frontmatter.js';

export interface ValidationIssue {
  severity: 'must-fix' | 'should-fix';
  check: string;
  message: string;
  file?: string;
}

export interface ValidationWarning {
  check: string;
  message: string;
  file?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationIssue[];
  warnings: ValidationWarning[];
}

interface NoteManifest {
  source_note: string;
  concept_notes: string[];
}

function toKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[()[\]{}'"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

/**
 * Validates drafts generated by the ingestion agent before promotion.
 * Returns errors (block promotion) and warnings (log but allow).
 */
export function validateDrafts(
  draftsDir: string,
  jobId: string,
  sourceFilename: string,
): ValidationResult {
  const errors: ValidationIssue[] = [];
  const warnings: ValidationWarning[] = [];

  // --- Manifest ---
  const manifestPath = join(draftsDir, `${jobId}-manifest.json`);
  if (!existsSync(manifestPath)) {
    errors.push({
      severity: 'must-fix',
      check: 'manifest-exists',
      message: `Manifest file not found at ${jobId}-manifest.json. You must create it after writing all notes.`,
    });
    return { valid: false, errors, warnings };
  }

  let manifest: NoteManifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    errors.push({
      severity: 'must-fix',
      check: 'manifest-valid-json',
      message: `Manifest file ${jobId}-manifest.json is not valid JSON.`,
    });
    return { valid: false, errors, warnings };
  }

  if (!manifest.source_note) {
    errors.push({
      severity: 'must-fix',
      check: 'manifest-has-source',
      message: 'Manifest is missing "source_note" field.',
    });
  }

  if (!Array.isArray(manifest.concept_notes)) {
    errors.push({
      severity: 'must-fix',
      check: 'manifest-has-concepts',
      message: 'Manifest is missing "concept_notes" array.',
    });
    return { valid: false, errors, warnings };
  }

  // --- Source note existence ---
  const sourceNotePath = manifest.source_note
    ? join(draftsDir, manifest.source_note)
    : null;

  if (!sourceNotePath || !existsSync(sourceNotePath)) {
    errors.push({
      severity: 'must-fix',
      check: 'source-note-exists',
      message: `Source note file "${manifest.source_note}" listed in manifest does not exist. Expected filename: ${jobId}-source.md`,
      file: manifest.source_note,
    });
  } else if (statSync(sourceNotePath).size === 0) {
    errors.push({
      severity: 'must-fix',
      check: 'source-note-empty',
      message: `Source note "${manifest.source_note}" is empty (0 bytes).`,
      file: manifest.source_note,
    });
  }

  // --- Concept note existence ---
  for (const conceptFile of manifest.concept_notes) {
    const conceptPath = join(draftsDir, conceptFile);
    if (!existsSync(conceptPath)) {
      errors.push({
        severity: 'must-fix',
        check: 'concept-note-exists',
        message: `Concept note "${conceptFile}" listed in manifest does not exist.`,
        file: conceptFile,
      });
    } else if (statSync(conceptPath).size === 0) {
      errors.push({
        severity: 'must-fix',
        check: 'concept-note-empty',
        message: `Concept note "${conceptFile}" is empty (0 bytes).`,
        file: conceptFile,
      });
    }
  }

  // --- Source note frontmatter ---
  if (
    sourceNotePath &&
    existsSync(sourceNotePath) &&
    statSync(sourceNotePath).size > 0
  ) {
    const content = readFileSync(sourceNotePath, 'utf-8');
    const { data: fm } = parseFrontmatter(content);

    const required: [string, string][] = [
      [
        'source_type',
        'source_type (paper|lecture|textbook-chapter|article|news)',
      ],
      ['source_file', 'source_file'],
      [
        'concepts_generated',
        'concepts_generated (array of slugified concept titles)',
      ],
      ['verification_status', 'verification_status'],
    ];

    for (const [field, desc] of required) {
      if (fm[field] === undefined || fm[field] === null) {
        errors.push({
          severity: 'must-fix',
          check: 'source-frontmatter',
          message: `Source note is missing required frontmatter field: ${desc}`,
          file: manifest.source_note,
        });
      }
    }

    if (fm.type !== 'source') {
      errors.push({
        severity: 'must-fix',
        check: 'source-frontmatter',
        message: `Source note has type "${fm.type}" but must be "source"`,
        file: manifest.source_note,
      });
    }

    // Check source_file matches expected pattern
    const expectedSourceFile = `upload/processed/${jobId}-${sourceFilename}`;
    if (fm.source_file && fm.source_file !== expectedSourceFile) {
      warnings.push({
        check: 'source-file-path',
        message: `Source note source_file is "${fm.source_file}" but expected "${expectedSourceFile}"`,
        file: manifest.source_note,
      });
    }

    // --- Consistency: concepts_generated vs actual concept notes ---
    if (
      Array.isArray(fm.concepts_generated) &&
      manifest.concept_notes.length > 0
    ) {
      const generatedSlugs = new Set(fm.concepts_generated as string[]);

      for (const conceptFile of manifest.concept_notes) {
        const cPath = join(draftsDir, conceptFile);
        if (!existsSync(cPath)) continue;
        try {
          const cContent = readFileSync(cPath, 'utf-8');
          const { data: cFm } = parseFrontmatter(cContent);
          if (cFm.title) {
            const expectedSlug = toKebabCase(cFm.title as string);
            if (!generatedSlugs.has(expectedSlug)) {
              errors.push({
                severity: 'should-fix',
                check: 'concepts-generated-match',
                message: `Concept "${cFm.title}" (slug: ${expectedSlug}) is not listed in source note's concepts_generated. Add it.`,
                file: manifest.source_note,
              });
            }
          }
        } catch {
          // Skip unreadable files
        }
      }
    }
  }

  // --- Concept note frontmatter ---
  for (const conceptFile of manifest.concept_notes) {
    const conceptPath = join(draftsDir, conceptFile);
    if (!existsSync(conceptPath) || statSync(conceptPath).size === 0) continue;

    const content = readFileSync(conceptPath, 'utf-8');
    const { data: fm } = parseFrontmatter(content);

    const required: [string, string][] = [
      ['topics', 'topics (non-empty array)'],
      ['source_doc', 'source_doc'],
      ['source_file', 'source_file'],
      ['source_pages', 'source_pages (array of page numbers)'],
      ['verification_status', 'verification_status'],
    ];

    for (const [field, desc] of required) {
      const val = fm[field];
      if (val === undefined || val === null) {
        errors.push({
          severity: 'must-fix',
          check: 'concept-frontmatter',
          message: `Concept note "${conceptFile}" is missing required frontmatter field: ${desc}`,
          file: conceptFile,
        });
      } else if (
        Array.isArray(val) &&
        val.length === 0 &&
        (field === 'topics' || field === 'source_pages')
      ) {
        errors.push({
          severity: 'must-fix',
          check: 'concept-frontmatter',
          message: `Concept note "${conceptFile}" has empty ${field} array — it must have at least one entry`,
          file: conceptFile,
        });
      }
    }

    if (fm.type !== 'concept') {
      errors.push({
        severity: 'must-fix',
        check: 'concept-frontmatter',
        message: `Concept note "${conceptFile}" has type "${fm.type}" but must be "concept"`,
        file: conceptFile,
      });
    }
  }

  // --- Quality warnings (don't block promotion) ---
  const allNoteFiles = [
    ...(manifest.source_note ? [manifest.source_note] : []),
    ...manifest.concept_notes,
  ];

  for (const noteFile of allNoteFiles) {
    const notePath = join(draftsDir, noteFile);
    if (!existsSync(notePath)) continue;

    const content = readFileSync(notePath, 'utf-8');
    const { content: body } = parseFrontmatter(content);

    // Check for citations
    if (!/\[\^[0-9]+\]/.test(body)) {
      warnings.push({
        check: 'has-citations',
        message: `Note "${noteFile}" has no footnote citations ([^N]). Every factual claim should cite its source.`,
        file: noteFile,
      });
    }

    // Check word count for concept notes
    if (noteFile.includes('-concept-')) {
      const wordCount = body.trim().split(/\s+/).length;
      if (wordCount < 100) {
        warnings.push({
          check: 'word-count',
          message: `Concept note "${noteFile}" is very short (${wordCount} words). Target is 200-500 words.`,
          file: noteFile,
        });
      } else if (wordCount > 600) {
        warnings.push({
          check: 'word-count',
          message: `Concept note "${noteFile}" is long (${wordCount} words). Consider splitting into multiple concepts.`,
          file: noteFile,
        });
      }
    }
  }

  const hasMustFix = errors.some((e) => e.severity === 'must-fix');
  return { valid: !hasMustFix, errors, warnings };
}

/**
 * Formats validation issues into a message for the agent to fix.
 */
export function formatValidationMessage(result: ValidationResult): string {
  const parts: string[] = [];

  if (result.errors.length > 0) {
    parts.push('## Validation Errors\n');
    parts.push(
      'The following issues MUST be fixed before your work can be accepted:\n',
    );
    for (const err of result.errors) {
      const fileRef = err.file ? ` (in ${err.file})` : '';
      parts.push(`- **[${err.severity}]** ${err.message}${fileRef}`);
    }
  }

  if (result.warnings.length > 0) {
    parts.push('\n## Warnings\n');
    parts.push('These are non-blocking but should be addressed if possible:\n');
    for (const warn of result.warnings) {
      const fileRef = warn.file ? ` (in ${warn.file})` : '';
      parts.push(`- ${warn.message}${fileRef}`);
    }
  }

  parts.push(
    '\nFix the issues above, update the manifest if needed, then write a new empty sentinel file to signal completion.',
  );

  return parts.join('\n');
}
