import { execFile } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { access, readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { promisify } from 'node:util';

import { EXTRACTION_TIMEOUT, EXTRACTIONS_DIR } from '../config.js';
import { cleanExtraction } from './extraction-cleaner.js';
import { logger } from '../logger.js';

const execFileAsync = promisify(execFile);

export interface ExtractionResult {
  contentPath: string;
  cleanContentPath: string;
  figuresDir: string;
  figures: string[];
  metadataPath: string;
  previewPdfPath: string | null;
}

export class Extractor {
  private pythonBin: string;
  private scriptPath: string;
  private extractionsDir: string;

  constructor(opts?: {
    pythonBin?: string;
    scriptPath?: string;
    extractionsDir?: string;
  }) {
    this.pythonBin =
      opts?.pythonBin ??
      join(import.meta.dirname, '..', '..', '.venv', 'bin', 'python3');
    this.scriptPath =
      opts?.scriptPath ??
      join(import.meta.dirname, '..', '..', 'scripts', 'docling-extract.py');
    this.extractionsDir = opts?.extractionsDir ?? EXTRACTIONS_DIR;
  }

  /** Returns the persistent directory for a given job's extraction artifacts. */
  getExtractionDir(jobId: string): string {
    return join(this.extractionsDir, jobId);
  }

  /**
   * Runs cleanExtraction on content.md and writes the result to content.clean.md.
   * Returns the path to content.clean.md.
   */
  cleanAndWrite(jobId: string): string {
    const dir = this.getExtractionDir(jobId);
    const rawPath = join(dir, 'content.md');
    const cleanPath = join(dir, 'content.clean.md');

    const raw = readFileSync(rawPath, 'utf-8');
    const cleaned = cleanExtraction(raw);
    writeFileSync(cleanPath, cleaned);

    const ratio =
      raw.length > 0 ? Math.round((1 - cleaned.length / raw.length) * 100) : 0;
    logger.info(
      {
        jobId,
        originalSize: raw.length,
        cleanedSize: cleaned.length,
        ratio: `${ratio}%`,
      },
      `Extraction cleanup: ${raw.length} → ${cleaned.length} chars (${ratio}% reduction)`,
    );

    return cleanPath;
  }

  /** Returns true if content.md, content.clean.md and metadata.json already exist for this job. */
  async hasArtifacts(jobId: string): Promise<boolean> {
    const dir = this.getExtractionDir(jobId);
    try {
      await access(join(dir, 'content.md'));
      await access(join(dir, 'content.clean.md'));
      await access(join(dir, 'metadata.json'));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Runs the Docling Python subprocess to extract a document.
   * Artifacts are written to `{extractionsDir}/{jobId}/`.
   * If artifacts already exist (hasArtifacts), returns immediately without
   * re-running extraction.
   */
  async extract(jobId: string, inputPath: string): Promise<ExtractionResult> {
    const outputDir = this.getExtractionDir(jobId);

    const { stdout } = await execFileAsync(
      this.pythonBin,
      [this.scriptPath, inputPath, outputDir],
      {
        timeout: EXTRACTION_TIMEOUT,
        maxBuffer: 10 * 1024 * 1024, // 10 MB
      },
    );

    const parsed = JSON.parse(stdout.trim()) as {
      status: string;
      outputDir?: string;
    };

    if (parsed.status !== 'ok') {
      throw new Error(`Docling extraction failed: ${JSON.stringify(parsed)}`);
    }

    const contentPath = join(outputDir, 'content.md');
    const metadataPath = join(outputDir, 'metadata.json');
    const figuresDir = join(outputDir, 'figures');

    // Collect figure filenames from the figures directory
    let figures: string[] = [];
    try {
      const entries = await readdir(figuresDir);
      figures = entries.filter((f) => !f.startsWith('.'));
    } catch {
      figures = [];
    }

    // Check for preview PDF (generated by soffice in the Python script)
    let previewPdfPath: string | null = null;
    const candidate = join(outputDir, 'preview.pdf');
    try {
      await access(candidate);
      previewPdfPath = candidate;
    } catch {
      previewPdfPath = null;
    }

    const cleanContentPath = this.cleanAndWrite(jobId);

    return {
      contentPath,
      cleanContentPath,
      figuresDir,
      figures,
      metadataPath,
      previewPdfPath,
    };
  }

  /** Removes the extraction directory for a job. */
  async cleanup(jobId: string): Promise<void> {
    const dir = this.getExtractionDir(jobId);
    await rm(dir, { recursive: true, force: true });
  }
}
