import { ZoteroWebClient } from './zotero-client.js';
import { logger } from '../logger.js';

export class ZoteroWriteBack {
  constructor(private readonly webClient: ZoteroWebClient) {}

  async writeBack(
    zoteroKey: string,
    sourceNoteContent: string,
    promotedPaths: string[],
  ): Promise<void> {
    try {
      const body = this.extractBody(sourceNoteContent);
      const html = this.buildNoteHtml(body, promotedPaths);

      await this.createNoteWithRetry(zoteroKey, html);
      await this.webClient.addTag(zoteroKey, 'vault:ingested');

      logger.info({ zoteroKey }, 'Zotero write-back completed');
    } catch (err) {
      logger.warn({ zoteroKey, err }, 'Zotero write-back failed — continuing');
    }
  }

  private async createNoteWithRetry(
    zoteroKey: string,
    html: string,
  ): Promise<void> {
    let version = await this.webClient.getLibraryVersion();
    try {
      await this.webClient.createChildNote(zoteroKey, html, version);
    } catch (err) {
      if (err instanceof Error && err.message.includes('412')) {
        version = await this.webClient.getLibraryVersion();
        await this.webClient.createChildNote(zoteroKey, html, version);
      } else {
        throw err;
      }
    }
  }

  private extractBody(content: string): string {
    const match = content.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
    return (match ? match[1] : content).trim();
  }

  private buildNoteHtml(markdownBody: string, promotedPaths: string[]): string {
    const date = new Date().toISOString().split('T')[0];
    const conceptCount = promotedPaths.filter((p) =>
      p.startsWith('concepts/'),
    ).length;
    const sourcePath = promotedPaths.find((p) => p.startsWith('sources/'));

    const bodyHtml = this.markdownToHtml(markdownBody);

    const parts = [
      '<h2>Source Summary</h2>',
      `<p>Generated by universityClaw on ${date}</p>`,
      '<hr/>',
      bodyHtml,
      '<hr/>',
    ];

    const links: string[] = [];
    if (sourcePath) links.push(`source: ${sourcePath}`);
    if (conceptCount > 0) links.push(`${conceptCount} concepts`);
    if (links.length > 0) {
      parts.push(`<p><em>Vault notes: ${links.join(', ')}</em></p>`);
    }

    return parts.join('\n');
  }

  private markdownToHtml(md: string): string {
    return md
      .split(/\n\n+/)
      .map((block) => {
        const trimmed = block.trim();
        if (!trimmed) return '';

        const headingMatch = trimmed.match(/^(#{1,6})\s+(.*)$/);
        if (headingMatch) {
          const level = headingMatch[1].length;
          return `<h${level}>${this.inlineFormat(headingMatch[2])}</h${level}>`;
        }

        if (trimmed.match(/^[-*]\s/m)) {
          const items = trimmed
            .split(/\n/)
            .filter((l) => l.trim())
            .map(
              (l) => `<li>${this.inlineFormat(l.replace(/^[-*]\s+/, ''))}</li>`,
            )
            .join('\n');
          return `<ul>\n${items}\n</ul>`;
        }

        return `<p>${this.inlineFormat(trimmed.replace(/\n/g, ' '))}</p>`;
      })
      .filter(Boolean)
      .join('\n');
  }

  private inlineFormat(text: string): string {
    return text
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/\[\[(.+?)\]\]/g, '$1');
  }
}
